version: '3'

services:
  www:
    build: .
    container_name: web_${PROJID}
    volumes:
      - ./www:/var/www/html:rw
    restart: always
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - db

  db:
    image: ${DBIMAGE}
    container_name: db_${PROJID}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_${PROJID}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASS}
      UPLOAD_LIMIT: 256M
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma_${PROJID}
    restart: always
    ports:
      - ${PMA_PORT}:80
    environment:
      PMA_HOST: db
      PMA_USER: ${USER}
      PMA_PASSWORD: ${PASS}
    depends_on:
      - db

volumes:
  db_data:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
