version: '3'

services:
  www:
    build: .
    container_name: web_${PROJID}
    volumes:
      - ./www:/var/www/html:rw
    restart: always
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - db

  db:
    image: ${DBIMAGE}
    container_name: db_${PROJID}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_${PROJID}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ./data/db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma_${PROJID}
    restart: always
    ports:
      - 9000:80
    environment:
      PMA_HOST: db
      PMA_USER: ${MA_USER}
      PMA_PASSWORD: ${MA_PASS}
    volumes:
      - ./data/pma.ini:/usr/local/etc/php/conf.d/phpmyadmin_custom.ini:ro
    depends_on:
      - db

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
